## SERVER
server:
  port: 8082
  compression:
    enabled: true
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

## LOGGER
logging:
  level:
    root: info
    org.springframework: info

## Swagger-UI
springdoc:
  api-docs:
    path: /products-kardex-hulk-store
  swagger-ui:
    path: /swagger-ui.html
  paths-to-exclude: /swagger-resources/**

## APPLICATION
spring:
  application:
    name: products-kardex-hulk-store
    version: v1.0.0
    log: ./logs/
    root: /kardex-api/${spring.application.name}/${spring.application.version}
    port: 8082
    services:
      methods:
        ping:
          name: PING
          path: /ping
        create:
          name: CREATE
          path: /create
        update:
          name: UPDATE
          path: /update
        delete:
          name: DELETE
          path: /delete
        find:
          name: FIND
          path: /find
        sales:
          name: FIND
          path: /sales
      names:
        product:
          name: PRODUCT
          path-product-update: /product-update
          path-product-create: /product-create
          path-product-query: /product-query
          path-product-sales: /product-sales

  main:
    allow-bean-definition-overriding: true

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/kardex_hulk_store?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&serverTimezone=GMT-5
      username: root
      password:
      encrypted:
        root: Sys73mHnLkS70r3@@
      hikari:
        pool-name: mysql-operating-credit-pools
        auto-commit: true
        allow-pool-suspension: false
        connection-timeout: 60000
        idle-timeout: 60000
        maximum-pool-size: 60
        minimum-idle: 20
        max-lifetime: 120000
        catalog: kardex_hulk_store
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

#Adapters for comunication others components
adapters:
  components:
    authentication:
      url: http://localhost:8083/kardex-api/auth-kardex-hulk-store/v1.0.0
      methods:
        confirm:
          root: /authentication-confirm/confirm